
settings:
  driver: MJO_suite.py
  long_name: MJO diagnostics suite (from AMWG variability diagnostic package)
  description: MJO CLIVAR suite (NCAR) 
  required_programs: ['python', 'ncl']
  required_ncl_scripts: ['contributed', 'gsn_code', 'gsn_csm', 'shea_util', 'diagnostics_cam']

# USAGE varlist
# var_name      time-frequency     [requirement]
#
# - var_name: as found in src/config_*.yml
# - freq: mon (monthly), day, 6hr, 3hr, 1hr
# - requirement = blank  (default = optional)                                          
#                      required (package cannot run without this)                           
#                      required unless field_name field_name2 ...
# - alternates: 
#
#   nb. if a variable is required at multiple time frequencies,
#       list it separately for each one
#
#          Clearly the developer can just leave out optional files
#          However, it is always nice to get an upfront warning of missing files

#daily_avg
varlist:
  - var_name: v200_var
    freq: day
    requirement: required
    alternates: [va_var]
  - var_name: u200_var
    freq: day
    requirement: required
    alternates: [ua_var]   
  - var_name: u850_var
    freq: day
    requirement: required
    alternates: [ua_var] 
  - var_name: v850_var
    freq: day
    requirement: required
    alternates: [va_var] 
  - var_name: rlut_var
    freq: day
    requirement: required
  - var_name: pr_var
    freq: day
    requirement: required 